index:
  path: /
  controller: App\Controller\PrehladController::index
#homepage:
#    path: /{_locale}
#    controller: App\Controller\PrehladController::index
#    locale: sk
#    requirements:
#     _locale : sk|en
